"""initial schema

Revision ID: fc5a4539a324
Revises: 
Create Date: 2026-03-17 16:24:45.925305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5a4539a324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('criteria', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.create_index('ix_badge_name', ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('avatar_filename', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('preferred_ai_model', sa.String(length=50), nullable=True),
    sa.Column('code_generation_style', sa.String(length=50), nullable=True),
    sa.Column('auto_explain_code', sa.Boolean(), nullable=True),
    sa.Column('show_line_numbers', sa.Boolean(), nullable=True),
    sa.Column('enable_animations', sa.Boolean(), nullable=True),
    sa.Column('enable_tooltips', sa.Boolean(), nullable=True),
    sa.Column('tooltip_delay', sa.Integer(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('auto_save_snippets', sa.Boolean(), nullable=True),
    sa.Column('public_profile', sa.Boolean(), nullable=True),
    sa.Column('show_activity', sa.Boolean(), nullable=True),
    sa.Column('snippet_visibility', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.create_index('ix_user_locked_until', ['locked_until'], unique=False)
        batch_op.create_index('ix_user_username', ['username'], unique=True)

    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.create_index('ix_chat_session_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_chat_session_user_id', ['user_id'], unique=False)

    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index('ix_collection_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_collection_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_collection_user_id', ['user_id'], unique=False)

    op.create_table('leetcode_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('leetcode_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('leetcode_problem', schema=None) as batch_op:
        batch_op.create_index('ix_leetcode_problem_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_leetcode_problem_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_leetcode_problem_title', ['title'], unique=True)

    op.create_table('multi_step_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('test_cases', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('layer1_architecture', sa.Text(), nullable=True),
    sa.Column('layer2_coder', sa.Text(), nullable=True),
    sa.Column('layer3_tester', sa.Text(), nullable=True),
    sa.Column('layer4_refiner', sa.Text(), nullable=True),
    sa.Column('final_code', sa.Text(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id')
    )
    with op.batch_alter_table('multi_step_result', schema=None) as batch_op:
        batch_op.create_index('ix_multi_step_result_result_id', ['result_id'], unique=False)
        batch_op.create_index('ix_multi_step_result_status', ['status'], unique=False)
        batch_op.create_index('ix_multi_step_result_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_multi_step_result_user_id', ['user_id'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index('ix_note_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_note_user_id', ['user_id'], unique=False)

    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.create_index('ix_point_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_point_user_id', ['user_id'], unique=False)

    op.create_table('user_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.create_index('ix_user_badge_badge_id', ['badge_id'], unique=False)
        batch_op.create_index('ix_user_badge_user_id', ['user_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index('ix_chat_message_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_chat_message_session_id', ['session_id'], unique=False)

    op.create_table('leetcode_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['leetcode_problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leetcode_solution', schema=None) as batch_op:
        batch_op.create_index('ix_leetcode_solution_approved', ['approved'], unique=False)
        batch_op.create_index('ix_leetcode_solution_problem_id', ['problem_id'], unique=False)
        batch_op.create_index('ix_leetcode_solution_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_leetcode_solution_user_id', ['user_id'], unique=False)

    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('thought_steps', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.create_index('ix_snippet_language', ['language'], unique=False)
        batch_op.create_index('ix_snippet_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_snippet_title', ['title'], unique=False)
        batch_op.create_index('ix_snippet_user_id', ['user_id'], unique=False)

    op.create_table('snippet_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snippet_version', schema=None) as batch_op:
        batch_op.create_index('ix_snippet_version_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_snippet_version_snippet_id', ['snippet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippet_version', schema=None) as batch_op:
        batch_op.drop_index('ix_snippet_version_snippet_id')
        batch_op.drop_index('ix_snippet_version_created_at')

    op.drop_table('snippet_version')
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.drop_index('ix_snippet_user_id')
        batch_op.drop_index('ix_snippet_title')
        batch_op.drop_index('ix_snippet_timestamp')
        batch_op.drop_index('ix_snippet_language')

    op.drop_table('snippet')
    with op.batch_alter_table('leetcode_solution', schema=None) as batch_op:
        batch_op.drop_index('ix_leetcode_solution_user_id')
        batch_op.drop_index('ix_leetcode_solution_timestamp')
        batch_op.drop_index('ix_leetcode_solution_problem_id')
        batch_op.drop_index('ix_leetcode_solution_approved')

    op.drop_table('leetcode_solution')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_session_id')
        batch_op.drop_index('ix_chat_message_created_at')

    op.drop_table('chat_message')
    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.drop_index('ix_user_badge_user_id')
        batch_op.drop_index('ix_user_badge_badge_id')

    op.drop_table('user_badge')
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_index('ix_point_user_id')
        batch_op.drop_index('ix_point_timestamp')

    op.drop_table('point')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_user_id')
        batch_op.drop_index('ix_note_timestamp')

    op.drop_table('note')
    with op.batch_alter_table('multi_step_result', schema=None) as batch_op:
        batch_op.drop_index('ix_multi_step_result_user_id')
        batch_op.drop_index('ix_multi_step_result_timestamp')
        batch_op.drop_index('ix_multi_step_result_status')
        batch_op.drop_index('ix_multi_step_result_result_id')

    op.drop_table('multi_step_result')
    with op.batch_alter_table('leetcode_problem', schema=None) as batch_op:
        batch_op.drop_index('ix_leetcode_problem_title')
        batch_op.drop_index('ix_leetcode_problem_timestamp')
        batch_op.drop_index('ix_leetcode_problem_difficulty')

    op.drop_table('leetcode_problem')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_user_id')
        batch_op.drop_index('ix_collection_timestamp')
        batch_op.drop_index('ix_collection_parent_id')

    op.drop_table('collection')
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_session_user_id')
        batch_op.drop_index('ix_chat_session_updated_at')

    op.drop_table('chat_session')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_index('ix_user_locked_until')
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_index('ix_badge_name')

    op.drop_table('badge')
    # ### end Alembic commands ###
